# Generated by Django 3.0.5 on 2020-05-04 16:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignUserCubic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField(blank=True, default=datetime.datetime(2020, 5, 4, 16, 23, 53, 965867, tzinfo=utc), null=True)),
                ('assigned_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('assigner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('cubic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.Cubic')),
            ],
            options={
                'unique_together': {('assigned_user', 'cubic')},
            },
        ),
    ]
