# Generated by Django 3.0.5 on 2020-05-04 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.PositiveIntegerField()),
                ('near_lab', models.BooleanField()),
                ('date', models.DateField(auto_now_add=True)),
                ('destination_date', models.DateField(blank=True, null=True)),
                ('business_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='custom_user.BusinessGroup')),
                ('business_group_near_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='custom_user.BusinessGroup')),
            ],
        ),
    ]
