# Generated by Django 3.0.5 on 2020-04-11 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom_user', '0001_initial'),
        ('facilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.PositiveIntegerField()),
                ('near_lab', models.BooleanField()),
                ('date', models.DateField(auto_now_add=True)),
                ('destination_date', models.DateField(blank=True, null=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='custom_user.Unit')),
                ('unit_near_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='custom_user.Unit')),
            ],
        ),
        migrations.CreateModel(
            name='AssignUserCubic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField(auto_now_add=True, null=True)),
                ('assigned_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('assigner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('cubic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.Cubic')),
            ],
            options={
                'unique_together': {('assigned_user', 'cubic')},
            },
        ),
    ]
