# Generated by Django 3.0.5 on 2020-04-11 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('focal_point', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='group',
            new_name='unit',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='group_near_by',
            new_name='unit_near_by',
        ),
    ]
