# Generated by Django 3.0.5 on 2020-04-11 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
        ('custom_user', '0002_auto_20200411_1748'),
        ('space_planner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assigngroupcubic',
            old_name='assigned_group',
            new_name='assigned_unit',
        ),
        migrations.AlterUniqueTogether(
            name='assigngroupcubic',
            unique_together={('cubic', 'assigned_unit')},
        ),
    ]
