# Generated by Django 3.0.4 on 2020-05-02 14:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('custom_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestToChangeCubic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField(default=datetime.datetime(2020, 5, 2, 14, 42, 8, 8754, tzinfo=utc))),
                ('status', models.CharField(choices=[('unread', 'unread'), ('in progress', 'in progress'), ('approved', 'approved'), ('denied', 'denied')], default='unread', max_length=100)),
                ('reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('cubic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facilities.Cubic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FocalPointRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_time_employees_amount', models.PositiveIntegerField(blank=True, null=True)),
                ('part_time_employees_amount', models.PositiveIntegerField(blank=True, null=True)),
                ('date', models.DateField(default=datetime.datetime(2020, 5, 2, 14, 42, 8, 10720, tzinfo=utc))),
                ('destination_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('unread', 'unread'), ('in progress', 'in progress'), ('approved', 'approved'), ('denied', 'denied')], default='unread', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('business_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='custom_user.BusinessGroup')),
                ('business_group_near_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='custom_user.BusinessGroup')),
                ('near_lab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='facilities.Space')),
            ],
        ),
    ]
