# Generated by Django 3.0.5 on 2020-04-11 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('employee_number', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('regular', 'regular'), ('space_planner', 'space_planner'), ('focal_point', 'focal_point')], max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('percentage', models.CharField(choices=[('full_time', 'full_time'), ('part_time', 'part_time')], max_length=100)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_user.Group')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
