# Generated by Django 3.0.4 on 2020-04-20 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessGroup',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('employee_number', models.CharField(default='1', max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('percentage', models.CharField(choices=[('full_time', 'full_time'), ('part_time', 'part_time')], default='full_time', max_length=100)),
                ('focal_point', models.BooleanField(default=False)),
                ('space_planner', models.BooleanField(default=False)),
                ('business_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_user.BusinessGroup')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
