# Generated by Django 3.0.5 on 2020-04-11 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0002_auto_20200411_1748'),
        ('custom_user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='Unit',
        ),
    ]
