# Generated by Django 3.0.5 on 2020-05-04 15:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('percentage', models.CharField(choices=[('full_time', 'full_time'), ('part_time', 'part_time')], max_length=100)),
                ('creation_date', models.DateField(default=django.utils.timezone.now)),
                ('business_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_user.BusinessGroup')),
            ],
        ),
    ]
